version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dictionary
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    ports:
      - 8081:8081
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
  adminer:
    image: adminer
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      ADMINER_DESIGN: dracula
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - 8080:8080
