name: Tests

on: push

jobs:
  testing:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      DB_HOST: localhost
      DB_NAME: dictionary_test
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
      JWT_SECRET: secret
      ACCESS_TOKEN_VALIDITY_DURATION_IN_SEC: 3600
    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: dictionary
          POSTGRES_PORT: 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '23.3.0'
          architecture: 'x64'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Setup database
        run: psql -d postgres://postgres:postgres@localhost:5432 -c 'CREATE DATABASE dictionary_test;'
      - name: Run Test Suite
        run: npm run test